export const oneLiners = [
  "Stop! Back away from that Wuzzle",
  "Hands off my Wuzzle!",
  "Wuzzle in the morning.  Wuzzle in the night.  Wuzzle, Wuzzle, Wuzzle because it just feels right.",
  "Where do you Wuzzle?",
  "Show me that Wuzzle!",
  "Sweet Wuzzle!",
  "Have you seen that guys Wuzzle?",
  "Wanna see my Wuzzle?",
  "Just got my ass licked by a Wuzzle.",
  "Have you seen my Wuzzle?",
  "Here Wuzzle, Wuzzle, Wuzzle.",
  "When did you last play with your Wuzzle?",
  "How many Wuzzle's did you have for breakfast?",
  "Rule #1: Don't play with your Wuzzle.",
  "How come you always get the Wuzzle?",
  "What you talking about Wuzzle?",
  "If there's a Wuzzle there's a way.",
  "Just got my ass handed to me by a Wuzzle.",
  "One o'clock, Two o'clock, Three o'clock, Wuzzle!",
  "Rule #2: Keep your Wuzzle to yourself.",
  "Wuzzle!",
  "Happy Wuzzle Day.",
  "Let the Wuzzle be with you.",
  "On the 8th day God played Wuzzle.",
  "Wuzzle.  The 8th wonder of the world.",
  "Just got my third dose of Wuzzle.",
  "Who touched my Wuzzle?",
  "Take two Wuzzles and call me in the morning.",
  "All I need is a good Wuzzle.",
  "Make sure you clean that Wuzzle.",
  "If you shake that Wuzzle more than twice, you're playing with it.",
  "Wuzzle. Anybody?",
  "I'm trying to watch my Wuzzle.",
  "Don't get your Wuzzle caught in that zipper.",
  "Hold your Wuzzle right there mister!",
  "Sometimes, I find myself dreaming about Wuzzles.",
  "Don't let your Wuzzle get the best of you.",
  "Nothing like a good Wuzzle.",
  "Now that's a Wuzzle!",
  "Shhh.  The Wuzzle is sleeping.",
  "Do you Wuzzle?",
  "Would you Wuzzle with a friend?",
  "Does your girlfriend know you Wuzzle?",
  "Even my Mom Wuzzles.",
  "I can't stop at one Wuzzle.",
  "One Wuzzle won't kill you.",
  "You can't get addicted to Wuzzle.",
  "It's always Wuzzle o'clock somewhere.",
  "Hang on ... just one more Wuzzle.",
  "Bullseye. Right between the Wuzzle.",
  "The Wuzzle didn't see it coming.",
  "What came first?  The chicken or the Wuzzle?",
  "Beam me up Wuzzle!",
  "Wuzzle, we have a problem!",
  "Oops.  I dropped my Wuzzle.",
  "For the love of Wuzzle.",
  "Don't let your Wuzzle catch you doing that!",
  "Big, bad and Wuzzle.",
  "That Wuzzle had it coming!",
  "Well call me a Wuzzle.",
  "Don't be such a Wuzzle.",
  "Wuzzle or not.  Here I come.",
  "What doesn't Wuzzle makes you stronger.",
  "Sometimes you just want to Wuzzle.",
  "Get that Wuzzle out of your mouth.",
  "I just got Wuzzled.",
  "Wuzzled. Again!",
  "Another day. Another Wuzzle.",
  "Don't just stand there. Wuzzle it.",
  "Snuzzle my Wuzzle.",
  "Just call me Wuzzle.",
  "And don't call me Wuzzle.",
  "00Wuzzle.",
  "That's Mister Wuzzle to you.",
  "If it's hard like a Wuzzle. Then is must be a Wuzzle.",
  "Show me that Wuzzle!",
  "Wuzzle UP!",
  "Wanna Wuzzle?",
  "When I grow up, I want to be a Wuzzle.",
  "Don't give me that Wuzzle.",
  "Let go my Wuzzle.",
  "I saw my Dad Wuzzling.",
  "One Wuzzle is never enough.",
  "Please pass me the Wuzzle.",
  "Down. Wuzzle. Down.",
  "10, 9, 8, ... 3, 2, 1, WUZZLE!",
  "What did you have for Wuzzle?",
  "Don't let that Wuzzle get away!",
  "Don't be such a Wuzzle.",
  "Wuzzles first.",
  "Can't live with Wuzzle. Can't live without.",
  "A happy Wuzzle is a happy life.",
  "Wuz up Wuzzle.",
  "Wuzzles are a girls best friend.",
  "Who wants the last Wuzzle.",
  "Once a Wuzzle. Always a Wuzzle.",
  "Stop trying to Wuzzle me.",
  "I've had enough Wuzzle for one day.",
  "Wuzzle and carry.",
  "Now where did I leave that Wuzzle.",
  "I love you Wuzzle.",
  "Wuzzle.  Do you come here often?",
  "It's hard to be a Wuzzle.",
  "Blame it on the Wuzzle.",
  "The Wuzzle must of done it.",
  "What the Wuzzle.",
  "Go Wuzzle yourself.",
  "Did I say you could Wuzzle there?",
  "Are you smarter than a Wuzzle?",
  "I'll take my Wuzzle medium rare.",
  "Would you like fries with your Wuzzle?",
  "Let me be the Wuzzle of that.",
  "Don't pet the Wuzzle.",
  "I think somebody forgot their Wuzzle.",
  "Look! Did you see that Wuzzle.",
  "Did you wash your Wuzzle before bed?",
  "Do you take this Wuzzle ...",
  "Why did the Wuzzle cross the road?",
  "1 Wuzzle + 1 Wuzzle = 3 Wuzzles",
  "Was that a shooting Wuzzle?",
  "I wonder if there are Wuzzles on Mars?",
  "Our home and native Wuzzle.",
  "This Wuzzles for you!",
  "Can I get a Wuzzle, Wuzzle?",
  "I think that Wuzzle ate my ...",
  "Life is like a box of Wuzzles.",
  "You really put your Wuzzle in your mouth that time.",
  "I think I just swallowed a Wuzzle.",
  "Wuzzle is only skin deep.",
  "Let the Wuzzle be the judge of that.",
  "Put your Wuzzle into it!",
  "What a cute Wuzzle.",
  "My Wuzzle is strictly paleo.",
  "Don't get my Wuzzle started.",
  "Can you keep a Wuzzle?",
  "Just Wuzzle it!",
  "The dog ate my Wuzzle.",
  "Wuzzlishious Baby!",
  "Is that a Wuzzle, or are you just happy to see me?",
  "Wuzzle like ... it won't go away.",
  "Did you check under the Wuzzle.",
  "Don't get your Wuzzle in a pickle.",
  "It takes 2 to Wuzzle.",
  "Hey! Can you grab me a Wuzzle.",
  "I can't stop thinking about my Wuzzle.",
  "When the going get tough, the Wuzzle kicks your ass."
];
